-- MySQL Script generated by MySQL Workbench
-- Thu May 12 12:15:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `oid` BIGINT(20) NOT NULL,
  `course_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `credit` DOUBLE NOT NULL,
  `assigned_instructor` VARCHAR(45) NULL,
  `enrolled_student` VARCHAR(45) NULL,
  `Coursecol` VARCHAR(45) NULL,
  `instructor_oid` INT NOT NULL,
  PRIMARY KEY (`oid`),
  CONSTRAINT `INSTRUCTOR_FK`
    FOREIGN KEY (`instructor_oid`)
    REFERENCES `mydb`.`instructor` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `INSTRUCTOR_FK_idx` ON `mydb`.`course` (`instructor_oid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`course_student_map`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_student_map` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_student_map` (
  `oid` BIGINT(30) NOT NULL,
  `student_oid` BIGINT(20) NOT NULL,
  `course_oid` BIGINT(20) NOT NULL,
  `course_state` VARCHAR(45) NOT NULL,
  `course_grade` DOUBLE NULL,
  PRIMARY KEY (`oid`),
  CONSTRAINT `STUDENT_FK`
    FOREIGN KEY (`student_oid`)
    REFERENCES `mydb`.`student` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COURSE_FK`
    FOREIGN KEY (`course_oid`)
    REFERENCES `mydb`.`course` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `STUDENT_FK_idx` ON `mydb`.`course_student_map` (`student_oid` ASC) VISIBLE;

CREATE INDEX `COURSE_FK_idx` ON `mydb`.`course_student_map` (`course_oid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `oid` INT NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(45) CHARACTER SET 'armscii8' NOT NULL,
  `person_oid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`oid`),
  CONSTRAINT `PERSON_FK`
    FOREIGN KEY (`person_oid`)
    REFERENCES `mydb`.`person` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `person_oid_UNIQUE` ON `mydb`.`instructor` (`person_oid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(25) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `role` VARCHAR(30) NOT NULL,
  `phone` BIGINT(20) NULL,
  PRIMARY KEY (`oid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `student_id` BIGINT(20) NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  `numerical_grade` DOUBLE NULL,
  `person_oid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`oid`),
  CONSTRAINT `PERSON_FK`
    FOREIGN KEY (`person_oid`)
    REFERENCES `mydb`.`person` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PERSON_FK_idx` ON `mydb`.`student` (`person_oid` ASC) VISIBLE;

CREATE UNIQUE INDEX `person_oid_UNIQUE` ON `mydb`.`student` (`person_oid` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
